# QC Weigh-in-Motion deliverables data
Parameter:
Check the data for the following:
1. Instances of missing data (e.g. times when there is no vehicle data for 5-10 mins between vehicles)
2. Instances of duplicated data (e.g. the same vehicle data displayed in the file more than once)
3. Formatting of the .TXT files
 
Additionally, please check the files for the following:
1. Speeds greater than 85 mph
2. Speeds less than 10 mph
3. Vehicles with GVW greater than 250 kips
4. Class 1 with GVW more than 3.0 kips
5. Class 2-3 with GVW more than 15 kips
6. Vehicles with ESALs greater than 70
7. Wt1 greater than 25 kips

In [55]:
import pandas as pd

pd.options.display.max_columns = None
from openpyxl import Workbook
from openpyxl.formatting.rule import CellIsRule
from openpyxl.styles import PatternFill

In [56]:
df1 = pd.read_csv("EastBound_InsideLane.csv")
df1

,Year,Month,Day,Hour,Minute,Second,Thousand of a second,Error Number,Record Type,Lane,Speed,Class,Length,GVW,ESAL,Weight A,Axle Spacing AB,Weight B,Axle Space BC,Weight C,Axle Spacing CD,Weight D,Axle Space DE,Weight E,Axle Space EF,Weight F,Axle Spacing FG,Weight G,Axle Space GH,Weight H,Axle Spacing HI,Weight I,Axle Space IJ,Weight J,Axle Spacing JK,Weight K,Axle Space KL,Weight L,Axle Spacing LM,Weight M,Axle Space MN,Weight N,Column43,Column44,Column45,Column46,Column47,Column48,Temp
0,22,11,1,0,24,57,0,0,12,2,79,3,12.1,3.1,0.0004,1.8,12.1,1.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54
1,22,11,1,0,31,20,0,0,12,2,68,3,11.6,3.3,0.0004,1.7,11.6,1.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54
2,22,11,1,0,37,48,0,0,12,2,69,2,8.8,2.1,0.0004,1.2,8.8,0.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54
3,22,11,1,0,41,29,0,0,12,2,76,2,9.4,2.3,0.0004,1.4,9.4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54
4,22,11,1,0,43,49,0,0,12,2,77,3,10.8,2.7,0.0004,1.4,10.8,1.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2970,22,11,1,23,37,27,0,0,12,2,76,2,9.1,2.2,0.0004,1.2,9.1,1.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,63
2971,22,11,1,23,49,7,0,0,12,2,73,3,13.5,5.7,0.0009,2.4,13.5,3.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,63
2972,22,11,1,23,51,16,0,0,12,2,75,3,12.1,3.9,0.0004,1.5,12.1,2.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,63
2973,22,11,1,23,52,23,0,0,12,2,62,2,9.4,4.0,0.0004,1.8,9.4,2.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,63
2974,22,11,1,23,58,50,0,0,12,2,76,3,12.0,3.4,0.0004,1.7,12.0,1.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,63

## Missing Data

In [57]:
df1.pivot_table(values = ['Second'], index = ['Hour'], columns = ['Minute'], aggfunc = 'count')

       Second                                                              \
Minute     0    1    2    3    4    5    6    7    8    9    10   11   12
Hour
0         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN
2         1.0  NaN  NaN  2.0  NaN  1.0  NaN  NaN  1.0  NaN  1.0  NaN  1.0
3         1.0  NaN  NaN  NaN  NaN  1.0  NaN  NaN  1.0  1.0  NaN  NaN  1.0
4         3.0  3.0  1.0  2.0  NaN  NaN  NaN  1.0  NaN  1.0  2.0  1.0  1.0
5         NaN  3.0  1.0  1.0  1.0  2.0  NaN  3.0  NaN  2.0  2.0  1.0  1.0
6         1.0  3.0  1.0  4.0  1.0  3.0  3.0  2.0  4.0  1.0  6.0  1.0  6.0
7         4.0  4.0  6.0  6.0  4.0  2.0  1.0  4.0  4.0  2.0  3.0  4.0  4.0
8         6.0  3.0  2.0  2.0  3.0  4.0  2.0  6.0  3.0  3.0  3.0  4.0  5.0
9         1.0  3.0  3.0  3.0  3.0  3.0  5.0  6.0  5.0  4.0  7.0  2.0  3.0
10        6.0  4.0  1.0  1.0  3.0  1.0  1.0  3.0  2.0  1.0  3.0  1.0  4.0
11        3.0  2.0  4.0  3.0  4.0  2.0  3.0  2.0  2.0  2.0  NaN  6.0  NaN
12        1.0  1.0  5.0  5.0  4.0  2.0  5.0  2.0  3.0  2.0  2.0  1.0  1.0
13        3.0  3.0  2.0  5.0  1.0  2.0  3.0  NaN  1.0  4.0  1.0  NaN  1.0
14        5.0  5.0  5.0  1.0  5.0  1.0  NaN  NaN  1.0  4.0  3.0  2.0  NaN
15        7.0  2.0  NaN  4.0  2.0  2.0  1.0  7.0  4.0  3.0  1.0  4.0  4.0
16        2.0  1.0  5.0  4.0  7.0  6.0  4.0  4.0  3.0  2.0  8.0  4.0  2.0
17        7.0  1.0  5.0  2.0  2.0  5.0  4.0  5.0  4.0  6.0  4.0  5.0  3.0
18        3.0  6.0  NaN  1.0  1.0  3.0  1.0  3.0  2.0  3.0  NaN  3.0  5.0
19        1.0  1.0  NaN  NaN  1.0  2.0  1.0  1.0  2.0  1.0  2.0  NaN  3.0
20        2.0  1.0  2.0  NaN  NaN  1.0  NaN  NaN  1.0  NaN  1.0  NaN  NaN
21        1.0  NaN  2.0  NaN  1.0  NaN  1.0  1.0  NaN  NaN  NaN  NaN  2.0
22        NaN  NaN  NaN  NaN  NaN  NaN  1.0  2.0  NaN  1.0  1.0  NaN  NaN
23        NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0

                                                                           \
Minute    13   14   15   16   17   18   19   20   21   22    23   24   25
Hour
0        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  1.0  NaN
1        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0   NaN  NaN  1.0
2        NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN  NaN   1.0  NaN  1.0
3        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0   NaN  NaN  NaN
4        1.0  1.0  2.0  NaN  NaN  NaN  2.0  NaN  NaN  1.0   2.0  NaN  1.0
5        2.0  3.0  1.0  NaN  1.0  2.0  2.0  1.0  1.0  2.0   1.0  NaN  4.0
6        4.0  4.0  5.0  5.0  4.0  3.0  4.0  2.0  4.0  3.0   5.0  9.0  5.0
7        3.0  6.0  4.0  6.0  5.0  1.0  8.0  6.0  4.0  3.0   3.0  3.0  4.0
8        2.0  5.0  1.0  6.0  7.0  2.0  1.0  3.0  4.0  3.0   1.0  3.0  1.0
9        2.0  3.0  9.0  2.0  1.0  NaN  5.0  NaN  2.0  4.0   5.0  3.0  5.0
10       1.0  1.0  2.0  2.0  NaN  2.0  1.0  4.0  1.0  7.0  14.0  1.0  4.0
11       3.0  3.0  1.0  2.0  1.0  7.0  1.0  1.0  3.0  4.0   2.0  2.0  3.0
12       3.0  1.0  4.0  3.0  4.0  3.0  1.0  3.0  5.0  3.0   4.0  3.0  3.0
13      10.0  2.0  5.0  2.0  3.0  4.0  4.0  5.0  2.0  4.0   3.0  5.0  3.0
14       4.0  6.0  3.0  2.0  9.0  6.0  9.0  4.0  6.0  1.0   7.0  4.0  3.0
15       NaN  4.0  1.0  2.0  3.0  3.0  6.0  5.0  8.0  7.0   3.0  8.0  1.0
16       4.0  7.0  3.0  5.0  3.0  4.0  5.0  6.0  2.0  4.0   2.0  5.0  7.0
17       2.0  1.0  4.0  2.0  4.0  8.0  3.0  4.0  3.0  3.0   4.0  NaN  5.0
18       3.0  2.0  2.0  2.0  1.0  2.0  2.0  1.0  2.0  1.0   6.0  1.0  5.0
19       1.0  1.0  2.0  2.0  2.0  1.0  2.0  3.0  NaN  1.0   1.0  NaN  3.0
20       1.0  2.0  NaN  1.0  NaN  3.0  2.0  NaN  NaN  1.0   1.0  1.0  NaN
21       1.0  NaN  1.0  NaN  2.0  1.0  NaN  2.0  NaN  1.0   1.0  1.0  3.0
22       NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN  3.0   1.0  2.0  1.0
23       NaN  1.0  NaN  NaN  NaN  NaN  1.0  1.0  NaN  NaN   NaN  NaN  NaN

                                                                           \
Minute   26   27   28   29   30   31   32   33    34   35   36    37   38
Hour
0       NaN  NaN  NaN  NaN  NaN  1.0  NaN  NaN   NaN  NaN  NaN   1.0  NaN
1       NaN  NaN  NaN  NaN  NaN  NaN  1.0  1.0   NaN  NaN  NaN   NaN  NaN
2       1.0  NaN  NaN  2.0  1.0  1.0  NaN  1.0   NaN  NaN  1.0   NaN  1.0
3       NaN  1.0  NaN  NaN  NaN  1.0  1.0  1.0   NaN  NaN  NaN   2.0  NaN
4       3.0  NaN  1.0  NaN  NaN  1.0  1.0  NaN   1.0  1.0  NaN   1.0  1.0
5       NaN  4.0  NaN  2.0  3.0  NaN  3.0  3.0   3.0  3.0  6.0   2.0  3.0
6       1.0  2.0  2.0  4.0  2.0  NaN  3.0  6.0   5.0  2.0  4.0   6.0  6.0
7       4.0  5.0  2.0  3.0  7.0  2.0  7.0  4.0  12.0  4.0  2.0   4.0  3.0
8       2.0  4.0  1.0  2.0  7.0  1.0  3.0  6.0   2.0  7.0  3.0   7.0  6.0
9       6.0  2.0  1.0  2.0  3.0  5.0  2.0  3.0   3.0  1.0  2.0   2.0  4.0
10      1.0  3.0  4.0  4.0  2.0  4.0  2.0  1.0   2.0  5.0  3.0   1.0  NaN
11      NaN  3.0  7.0  1.0  NaN  2.0  5.0  NaN   1.0  1.0  3.0   3.0  3.0
12      2.0  2.0  3.0  1.0  5.0  1.0  3.0  5.0   NaN  1.0  2.0   6.0  5.0
13      2.0  4.0  2.0  5.0  4.0  2.0  5.0  4.0   4.0  6.0  1.0   4.0  4.0
14      4.0  2.0  NaN  1.0  2.0  4.0  6.0  2.0   5.0  3.0  4.0  11.0  2.0
15      NaN  2.0  3.0  1.0  2.0  4.0  1.0  5.0   4.0  5.0  2.0   3.0  5.0
16      4.0  4.0  7.0  4.0  6.0  4.0  3.0  1.0   7.0  3.0  3.0   4.0  8.0
17      NaN  5.0  6.0  6.0  4.0  4.0  3.0  4.0   7.0  3.0  6.0   3.0  7.0
18      3.0  7.0  2.0  5.0  1.0  3.0  1.0  2.0   1.0  1.0  1.0   3.0  NaN
19      1.0  4.0  1.0  2.0  NaN  2.0  4.0  1.0   NaN  2.0  NaN   1.0  1.0
20      NaN  2.0  1.0  2.0  1.0  NaN  2.0  NaN   NaN  NaN  1.0   2.0  4.0
21      NaN  NaN  3.0  2.0  NaN  2.0  1.0  NaN   1.0  2.0  NaN   NaN  NaN
22      NaN  NaN  NaN  NaN  NaN  NaN  1.0  1.0   NaN  2.0  NaN   1.0  1.0
23      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  1.0  1.0   1.0  NaN

                                                                            \
Minute   39   40   41   42   43   44    45    46   47   48   49   50    51
Hour
0       NaN  NaN  1.0  NaN  1.0  NaN   NaN   1.0  NaN  NaN  NaN  NaN   NaN
1       NaN  1.0  NaN  1.0  NaN  NaN   NaN   NaN  NaN  NaN  NaN  NaN   1.0
2       1.0  NaN  NaN  NaN  1.0  NaN   NaN   NaN  NaN  NaN  NaN  1.0   NaN
3       NaN  3.0  NaN  1.0  NaN  1.0   1.0   NaN  2.0  1.0  1.0  1.0   NaN
4       2.0  NaN  NaN  NaN  1.0  2.0   NaN   NaN  NaN  2.0  1.0  2.0   NaN
5       4.0  5.0  4.0  1.0  3.0  2.0   NaN   3.0  3.0  2.0  3.0  1.0   2.0
6       6.0  1.0  5.0  5.0  5.0  3.0   4.0   5.0  4.0  5.0  3.0  4.0   9.0
7       7.0  4.0  3.0  8.0  4.0  5.0  10.0   8.0  3.0  2.0  2.0  8.0   2.0
8       2.0  2.0  2.0  1.0  2.0  1.0   3.0   2.0  5.0  7.0  1.0  NaN  10.0
9       5.0  4.0  3.0  8.0  3.0  1.0   4.0   1.0  1.0  3.0  4.0  2.0   6.0
10      2.0  4.0  4.0  3.0  NaN  4.0   1.0   NaN  4.0  2.0  2.0  3.0   NaN
11      NaN  4.0  5.0  1.0  NaN  1.0   7.0   1.0  3.0  NaN  3.0  3.0   2.0
12      4.0  1.0  3.0  NaN  2.0  4.0   1.0   2.0  5.0  3.0  3.0  2.0   3.0
13      1.0  2.0  2.0  5.0  6.0  3.0   3.0   4.0  3.0  3.0  3.0  NaN   2.0
14      2.0  3.0  2.0  NaN  2.0  4.0   3.0   3.0  3.0  4.0  1.0  2.0   4.0
15      3.0  2.0  5.0  3.0  5.0  8.0   1.0  14.0  2.0  3.0  4.0  3.0   4.0
16      9.0  5.0  5.0  5.0  2.0  4.0   5.0   2.0  6.0  5.0  4.0  4.0   3.0
17      1.0  4.0  6.0  4.0  2.0  7.0   4.0   2.0  4.0  3.0  5.0  1.0   2.0
18      1.0  2.0  NaN  4.0  1.0  1.0   1.0   NaN  2.0  2.0  2.0  5.0   NaN
19      2.0  1.0  3.0  1.0  1.0  1.0   NaN   1.0  NaN  NaN  2.0  NaN   1.0
20      NaN  NaN  1.0  2.0  2.0  1.0   NaN   1.0  1.0  2.0  NaN  NaN   NaN
21      2.0  NaN  NaN  NaN  NaN  1.0   1.0   4.0  1.0  NaN  NaN  NaN   1.0
22      1.0  1.0  NaN  NaN  NaN  NaN   NaN   1.0  1.0  1.0  NaN  1.0   NaN
23      NaN  NaN  NaN  NaN  NaN  NaN   NaN   NaN  NaN  NaN  1.0  NaN   1.0


Minute   52   53   54   55   56   57   58   59
Hour
0       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1       NaN  1.0  NaN  NaN  1.0  NaN  NaN  NaN
2       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3       1.0  NaN  NaN  1.0  NaN  2.0  NaN  NaN
4       NaN  1.0  NaN  2.0  NaN  4.0  1.0  NaN
5       NaN  1.0  5.0  3.0  1.0  1.0  1.0  3.0
6       3.0  5.0  2.0  1.0  5.0  1.0  3.0  3.0
7       7.0  2.0  NaN  4.0  2.0  3.0  8.0  1.0
8       7.0  4.0  3.0  1.0  3.0  6.0  5.0  2.0
9       3.0  5.0  1.0  4.0  2.0  1.0  2.0  5.0
10      5.0  2.0  4.0  4.0  1.0  NaN  3.0  3.0
11      NaN  4.0  3.0  1.0  7.0  5.0  4.0  3.0
12      2.0  3.0  2.0  2.0  1.0  3.0  5.0  2.0
13      1.0  5.0  1.0  7.0  4.0  2.0  2.0  3.0
14      3.0  4.0  6.0  1.0  NaN  2.0  3.0  3.0
15      4.0  1.0  8.0  1.0  8.0  2.0  1.0  3.0
16      2.0  1.0  4.0  3.0  1.0  2.0  7.0  1.0
17      2.0  4.0  2.0  2.0  3.0  1.0  2.0  5.0
18      2.0  1.0  NaN  3.0  4.0  1.0  1.0  1.0
19      2.0  NaN  2.0  NaN  1.0  1.0  1.0  1.0
20      2.0  NaN  NaN  1.0  1.0  NaN  2.0  NaN
21      NaN  1.0  NaN  NaN  NaN  NaN  1.0  2.0
22      NaN  NaN  NaN  1.0  NaN  1.0  NaN  NaN
23      1.0  NaN  NaN  NaN  NaN  NaN  1.0  NaN

## Duplicates
Check if there are more than six rows stored the same value consecutively within column Class and Speed

In [58]:
df1["SpeedClass"] = df1["Speed"].astype(str) + "-" + df1["Class"].astype(str)
df1.head()

,Year,Month,Day,Hour,Minute,Second,Thousand of a second,Error Number,Record Type,Lane,Speed,Class,Length,GVW,ESAL,Weight A,Axle Spacing AB,Weight B,Axle Space BC,Weight C,Axle Spacing CD,Weight D,Axle Space DE,Weight E,Axle Space EF,Weight F,Axle Spacing FG,Weight G,Axle Space GH,Weight H,Axle Spacing HI,Weight I,Axle Space IJ,Weight J,Axle Spacing JK,Weight K,Axle Space KL,Weight L,Axle Spacing LM,Weight M,Axle Space MN,Weight N,Column43,Column44,Column45,Column46,Column47,Column48,Temp,SpeedClass
0,22,11,1,0,24,57,0,0,12,2,79,3,12.1,3.1,0.0004,1.8,12.1,1.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,79-3
1,22,11,1,0,31,20,0,0,12,2,68,3,11.6,3.3,0.0004,1.7,11.6,1.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,68-3
2,22,11,1,0,37,48,0,0,12,2,69,2,8.8,2.1,0.0004,1.2,8.8,0.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,69-2
3,22,11,1,0,41,29,0,0,12,2,76,2,9.4,2.3,0.0004,1.4,9.4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,76-2
4,22,11,1,0,43,49,0,0,12,2,77,3,10.8,2.7,0.0004,1.4,10.8,1.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,77-3

In [67]:
def duplicatedSpeedClass(x):
    #define length variable
    length = len(x)
    #define duplicates list
    duplicates = []
    
    #use for loop within range from first row to last row
    for i in range(0, length-1):
        #this conditional statement aims to find five consecutive duplicacies, should you need to find more or less 
        #than five duplicacies, edit the following statement by adding or removing "and x[i] == x[i+(n)"]
        if x[i] == x[i+1] and x[i] == x[i+2] and x[i] == x[i+3] and x[i] == x[i+4]:
                #add the index into "duplicates" list. If the conditional statement above was changed, the list 
                #inside extend() method should follow accordingly
                duplicates.extend([i, i+1, i+2, i+3, i+4])
                #sometimes there will be duplicacies within "duplicates" list above. To remove any duplicacies, we need to
                #convert the "duplicates" list to a set and then back to a list, cause sets only contain unique elements
                duplicates_unique = list(set(duplicates))
    
    #the "duplicates_uniques" is the final result in this function
    return duplicates_unique

print(duplicatedSpeedClass(df1["SpeedClass"]))

[33, 34, 35, 36, 37, 38, 39, 40, 41, 43, 44, 45, 46, 47, 62, 63, 64, 65, 66, 67, 68, 69, 70, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90]

In [60]:
df1.iloc[duplicatedSpeedClass(df1["SpeedClass"])]

,Year,Month,Day,Hour,Minute,Second,Thousand of a second,Error Number,Record Type,Lane,Speed,Class,Length,GVW,ESAL,Weight A,Axle Spacing AB,Weight B,Axle Space BC,Weight C,Axle Spacing CD,Weight D,Axle Space DE,Weight E,Axle Space EF,Weight F,Axle Spacing FG,Weight G,Axle Space GH,Weight H,Axle Spacing HI,Weight I,Axle Space IJ,Weight J,Axle Spacing JK,Weight K,Axle Space KL,Weight L,Axle Spacing LM,Weight M,Axle Space MN,Weight N,Column43,Column44,Column45,Column46,Column47,Column48,Temp,SpeedClass
33,22,11,1,2,38,21,0,0,12,2,75,2,10.1,2.4,0.0004,1.3,10.1,1.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,53,75-2
34,22,11,1,2,39,56,0,0,12,2,75,2,9.7,2.8,0.0004,1.5,9.7,1.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,53,75-2
35,22,11,1,2,43,52,0,0,12,2,75,2,56.0,30.6,0.0531,8.2,17.3,7.0,4.2,5.6,30.3,5.0,4.2,4.9,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,53,75-2
36,22,11,1,2,50,24,0,0,12,2,75,2,12.4,3.4,0.0004,1.8,12.4,1.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,53,75-2
37,22,11,1,3,0,10,0,0,12,2,75,2,51.6,34.1,0.1363,10.2,12.1,9.5,4.3,6.8,31.1,4.1,4.1,3.5,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,53,75-2
38,22,11,1,3,5,7,0,0,12,2,75,2,49.2,87.7,2.0059,8.1,15.2,18.5,4.5,18.4,20.8,7.0,4.3,18.5,4.4,17.1,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,53,75-2
39,22,11,1,3,8,15,0,0,12,2,75,2,11.8,3.4,0.0004,1.8,11.8,1.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,53,75-2
40,22,11,1,3,9,37,0,0,12,2,75,2,13.3,3.5,0.0004,1.9,13.3,1.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,53,75-2
41,22,11,1,3,12,16,0,0,12,2,75,2,9.6,2.7,0.0004,1.3,9.6,1.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,53,75-2
43,22,11,1,3,27,12,0,0,12,2,75,2,14.4,4.0,0.0004,2.4,14.4,1.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,53,75-2
44,22,11,1,3,31,48,0,0,12,2,75,2,11.6,2.9,0.0004,1.6,11.6,1.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,53,75-2
45,22,11,1,3,32,44,0,0,12,2,75,2,13.2,4.2,0.0004,2.2,13.2,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,53,75-2
46,22,11,1,3,33,9,0,0,12,2,75,2,8.8,2.4,0.0004,1.3,8.8,1.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,53,75-2
47,22,11,1,3,37,16,0,0,12,2,75,2,8.9,1.8,0.0004,1.1,8.9,0.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,53,75-2
62,22,11,1,3,57,26,0,0,12,2,68,2,9.4,2.3,0.0004,1.3,9.4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,53,68-2
63,22,11,1,3,57,47,0,0,12,2,68,2,10.1,2.4,0.0004,1.1,10.1,1.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,53,68-2
64,22,11,1,4,0,34,0,0,12,2,68,2,11.8,2.6,0.0004,1.4,11.8,1.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,68-2
65,22,11,1,4,0,52,0,0,12,2,68,2,14.3,5.1,0.0004,2.2,14.3,2.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,68-2
66,22,11,1,4,0,52,0,0,12,2,68,2,12.7,6.7,0.0014,3.2,12.7,3.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,68-2
67,22,11,1,4,1,29,0,0,12,2,68,2,13.0,4.9,0.0004,2.4,13.0,2.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,68-2
68,22,11,1,4,1,30,0,0,12,2,68,2,12.1,3.0,0.0004,1.6,12.1,1.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,68-2
69,22,11,1,4,1,38,0,0,12,2,68,2,9.9,2.7,0.0004,1.4,9.9,1.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,68-2
70,22,11,1,4,2,38,0,0,12,2,68,2,13.0,4.1,0.0004,2.3,13.0,1.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,68-2
78,22,11,1,4,12,32,0,0,12,2,75,2,9.3,2.0,0.0004,1.1,9.3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,75-2
79,22,11,1,4,13,55,0,0,12,2,75,2,9.8,3.5,0.0004,1.7,9.8,1.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,75-2
80,22,11,1,4,14,32,0,0,12,2,75,2,12.1,3.2,0.0004,1.6,12.1,1.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,75-2
81,22,11,1,4,15,21,0,0,12,2,75,2,9.1,2.4,0.0004,1.2,9.1,1.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,75-2
82,22,11,1,4,15,55,0,0,12,2,75,2,9.8,3.0,0.0004,1.5,9.8,1.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,75-2
83,22,11,1,4,19,3,0,0,12,2,75,2,11.6,3.4,0.0004,1.7,11.6,1.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,75-2
84,22,11,1,4,19,16,0,0,12,2,75,2,10.4,2.9,0.0004,1.6,10.4,1.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,75-2
85,22,11,1,4,22,58,0,0,12,2,75,2,8.4,1.6,0.0004,1.0,8.4,0.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,75-2
86,22,11,1,4,23,20,0,0,12,2,75,2,12.2,2.9,0.0004,1.6,12.2,1.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,75-2
87,22,11,1,4,23,44,0,0,12,2,75,2,9.1,2.9,0.0004,1.5,9.1,1.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,75-2
88,22,11,1,4,25,8,0,0,12,2,75,2,53.8,37.6,0.1288,10.8,14.4,7.3,4.3,7.1,31.1,6.0,4.0,6.3,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,75-2
89,22,11,1,4,26,3,0,0,12,2,75,2,11.8,3.0,0.0004,1.5,11.8,1.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,75-2
90,22,11,1,4,26,34,0,0,12,2,75,2,52.7,75.7,2.1622,8.1,17.5,18.0,4.4,18.3,26.5,16.9,4.3,14.4,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1:SORT*,0,1,0,0,0,54,75-2

## Additional Check

### 1. Speed greater than 85 mph

In [163]:
df1[df1["Speed"] > 85].sort_values("Speed")

,Year,Month,Day,Hour,Minute,Second,Thousand of a second,Error Number,Record Type,Lane,Speed,Class,Length,GVW,ESAL,Weight A,...,Weight J,Axle Spacing JK,Weight K,Axle Space KL,Weight L,Axle Spacing LM,Weight M,Axle Space MN,Weight N,Column43,Column44,Column45,Column46,Column47,Column48,Temp
3385,22,11,11,23,24,29,0,0,12,2,87.0,2,9.4,1.6,0.0004,0.8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1:SORT*,0,1,0,0,0,63
2374,22,11,11,16,26,5,0,0,12,2,87.0,2,9.6,2.4,0.0004,1.3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1:SORT*,0,1,0,0,0,77
2252,22,11,11,16,1,47,0,0,12,2,87.0,2,9.1,2.5,0.0004,1.3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1:SORT*,0,1,0,0,0,77
2232,22,11,11,15,59,14,0,0,12,2,87.0,3,12.1,2.7,0.0004,1.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1:SORT*,0,1,0,0,0,78
2207,22,11,11,15,54,57,0,0,12,2,87.0,2,9.4,2.8,0.0004,1.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1:SORT*,0,1,0,0,0,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
924,22,11,11,10,41,19,0,0,12,2,94.0,3,12.7,3.3,0.0004,1.9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1:SORT*,0,1,0,0,0,72
1948,22,11,11,15,10,26,0,0,12,2,96.0,2,9.3,2.1,0.0004,1.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1:SORT*,0,1,0,0,0,78
1984,22,11,11,15,18,8,0,0,12,2,97.0,3,13.1,3.1,0.0004,1.6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1:SORT*,0,1,0,0,0,78
2081,22,11,11,15,35,52,0,0,12,2,97.0,2,9.0,4.9,0.0004,2.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1:SORT*,0,1,0,0,0,78
2602,22,11,11,17,9,56,0,0,12,2,103.0,2,8.9,2.8,0.0004,1.6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1:SORT*,0,1,0,0,0,74

In [164]:
df1[df1["Speed"] > 85].groupby('Speed').Speed.count()

Speed
87.0     19
88.0     22
89.0      8
91.0      9
92.0      5
94.0      6
96.0      1
97.0      2
103.0     1
Name: Speed, dtype: int64

### 2. Speed less than 10 mph

In [165]:
df1[df1["Speed"] < 10].sort_values("Speed")

Empty DataFrame
Columns: [Year, Month, Day, Hour, Minute, Second, Thousand of a second, Error Number, Record Type, Lane, Speed, Class, Length, GVW, ESAL, Weight A, Axle Spacing AB, Weight B, Axle Space BC, Weight C, Axle Spacing CD, Weight D, Axle Space DE, Weight E, Axle Space EF, Weight F, Axle Spacing FG, Weight G, Axle Space GH, Weight H, Axle Spacing HI, Weight I, Axle Space IJ, Weight J, Axle Spacing JK, Weight K, Axle Space KL, Weight L, Axle Spacing LM, Weight M, Axle Space MN, Weight N, Column43, Column44, Column45, Column46, Column47, Column48, Temp]
Index: []

[0 rows x 49 columns]

In [166]:
df1[df1["Speed"] < 10].groupby('Speed').Speed.count()

Series([], Name: Speed, dtype: int64)

### 3. Vehicle with GVW greater than 250 kips

In [167]:
df1[df1["GVW"] > 250].sort_values("GVW")

Empty DataFrame
Columns: [Year, Month, Day, Hour, Minute, Second, Thousand of a second, Error Number, Record Type, Lane, Speed, Class, Length, GVW, ESAL, Weight A, Axle Spacing AB, Weight B, Axle Space BC, Weight C, Axle Spacing CD, Weight D, Axle Space DE, Weight E, Axle Space EF, Weight F, Axle Spacing FG, Weight G, Axle Space GH, Weight H, Axle Spacing HI, Weight I, Axle Space IJ, Weight J, Axle Spacing JK, Weight K, Axle Space KL, Weight L, Axle Spacing LM, Weight M, Axle Space MN, Weight N, Column43, Column44, Column45, Column46, Column47, Column48, Temp]
Index: []

[0 rows x 49 columns]

In [168]:
df1[df1["GVW"] > 250].groupby("GVW").GVW.count()

Series([], Name: GVW, dtype: int64)

### 4. Class 1 with GVW more than 3.0 kips

In [169]:
# Define Criteria 1 (Cr1):
Cr1 = df1["Class"] == 1

#Define Criteria 2 (Cr2):
Cr2 = df1["GVW"] > 3

df1[Cr1 & Cr2]

Empty DataFrame
Columns: [Year, Month, Day, Hour, Minute, Second, Thousand of a second, Error Number, Record Type, Lane, Speed, Class, Length, GVW, ESAL, Weight A, Axle Spacing AB, Weight B, Axle Space BC, Weight C, Axle Spacing CD, Weight D, Axle Space DE, Weight E, Axle Space EF, Weight F, Axle Spacing FG, Weight G, Axle Space GH, Weight H, Axle Spacing HI, Weight I, Axle Space IJ, Weight J, Axle Spacing JK, Weight K, Axle Space KL, Weight L, Axle Spacing LM, Weight M, Axle Space MN, Weight N, Column43, Column44, Column45, Column46, Column47, Column48, Temp]
Index: []

[0 rows x 49 columns]

In [170]:
df1[Cr1 & Cr2].groupby("GVW").GVW.count()

Series([], Name: GVW, dtype: int64)

### 5. Class 2 & 3 with GVW more than 15 kips

In [171]:
# Define Criteria 3 (Cr3):
Cr3 = df1["Class"].between(2, 3)

#Define Criteria 4 (Cr4):
Cr4 = df1["GVW"] > 15

df1[Cr3 & Cr4]

Empty DataFrame
Columns: [Year, Month, Day, Hour, Minute, Second, Thousand of a second, Error Number, Record Type, Lane, Speed, Class, Length, GVW, ESAL, Weight A, Axle Spacing AB, Weight B, Axle Space BC, Weight C, Axle Spacing CD, Weight D, Axle Space DE, Weight E, Axle Space EF, Weight F, Axle Spacing FG, Weight G, Axle Space GH, Weight H, Axle Spacing HI, Weight I, Axle Space IJ, Weight J, Axle Spacing JK, Weight K, Axle Space KL, Weight L, Axle Spacing LM, Weight M, Axle Space MN, Weight N, Column43, Column44, Column45, Column46, Column47, Column48, Temp]
Index: []

[0 rows x 49 columns]

In [172]:
df1[Cr3 & Cr4].groupby("GVW").GVW.count()

Series([], Name: GVW, dtype: int64)

### 6. ESALs greater than 70

In [173]:
df1[df1["ESAL"] > 70].sort_values("ESAL")

Empty DataFrame
Columns: [Year, Month, Day, Hour, Minute, Second, Thousand of a second, Error Number, Record Type, Lane, Speed, Class, Length, GVW, ESAL, Weight A, Axle Spacing AB, Weight B, Axle Space BC, Weight C, Axle Spacing CD, Weight D, Axle Space DE, Weight E, Axle Space EF, Weight F, Axle Spacing FG, Weight G, Axle Space GH, Weight H, Axle Spacing HI, Weight I, Axle Space IJ, Weight J, Axle Spacing JK, Weight K, Axle Space KL, Weight L, Axle Spacing LM, Weight M, Axle Space MN, Weight N, Column43, Column44, Column45, Column46, Column47, Column48, Temp]
Index: []

[0 rows x 49 columns]

In [174]:
df1[df1["ESAL"] > 70].groupby("ESAL").count()

Empty DataFrame
Columns: [Year, Month, Day, Hour, Minute, Second, Thousand of a second, Error Number, Record Type, Lane, Speed, Class, Length, GVW, Weight A, Axle Spacing AB, Weight B, Axle Space BC, Weight C, Axle Spacing CD, Weight D, Axle Space DE, Weight E, Axle Space EF, Weight F, Axle Spacing FG, Weight G, Axle Space GH, Weight H, Axle Spacing HI, Weight I, Axle Space IJ, Weight J, Axle Spacing JK, Weight K, Axle Space KL, Weight L, Axle Spacing LM, Weight M, Axle Space MN, Weight N, Column43, Column44, Column45, Column46, Column47, Column48, Temp]
Index: []

[0 rows x 48 columns]

### 7. Wt1 greater than 25 kips

In [175]:
df1[df1["Weight A"] > 25].sort_values("Weight A")

,Year,Month,Day,Hour,Minute,Second,Thousand of a second,Error Number,Record Type,Lane,Speed,Class,Length,GVW,ESAL,Weight A,...,Weight J,Axle Spacing JK,Weight K,Axle Space KL,Weight L,Axle Spacing LM,Weight M,Axle Space MN,Weight N,Column43,Column44,Column45,Column46,Column47,Column48,Temp
2308,22,11,11,16,14,18,0,0,12,2,73.0,6,25.8,62.8,5.0702,25.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1:SORT*,0,1,0,0,0,77

In [176]:
df1[df1["Weight A"] > 25].groupby("Weight A").count()

,Year,Month,Day,Hour,Minute,Second,Thousand of a second,Error Number,Record Type,Lane,Speed,Class,Length,GVW,ESAL,Axle Spacing AB,...,Weight J,Axle Spacing JK,Weight K,Axle Space KL,Weight L,Axle Spacing LM,Weight M,Axle Space MN,Weight N,Column43,Column44,Column45,Column46,Column47,Column48,Temp
Weight A,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
25.7,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1